;;; org-glance-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-glance.el

(register-definition-prefixes "org-glance" '("org-glance-"))


;;; Generated autoloads from org-glance-datetime-mode.el

(register-definition-prefixes "org-glance-datetime-mode" '("-org-glance-datetime:local-timestamps" "org-glance-datetime-mode"))


;;; Generated autoloads from org-glance-filter.el

(register-definition-prefixes "org-glance-filter" '("org-glance-filter"))


;;; Generated autoloads from org-glance-graph.el

(register-definition-prefixes "org-glance-graph" '("org-glance-"))


;;; Generated autoloads from org-glance-headline.el

(register-definition-prefixes "org-glance-headline" '("org-glance-headline"))


;;; Generated autoloads from org-glance-material.el

(register-definition-prefixes "org-glance-material" '("org-glance-"))


;;; Generated autoloads from org-glance-overview.el

(register-definition-prefixes "org-glance-overview" '("org-glance-overview"))


;;; Generated autoloads from org-glance-table.el

(autoload 'org-glance-table "org-glance-table" "\
Browse the graph as a sortable, badge-coloured table, optionally filtered.
Interactively, prompt for a tag (empty input = no tag constraint) and overlay it
on the ambient `org-glance-filter-spec' (default: active headlines) -- exactly
like `org-glance-overview', but rendered as a flat table.  Sort with `^' (sorts
by the column at point; repeat toggles direction, `C-u ^' adds a tie-breaker);
act on the row at point with RET/m, o, e.

(fn &optional TAG)" t)
(register-definition-prefixes "org-glance-table" '("org-glance-table-"))


;;; Generated autoloads from org-glance-tag-config.el

(autoload 'org-glance-tag-config-edit "org-glance-tag-config" "\
Open the tag-configuration file for editing, creating a stub if absent." t)
(register-definition-prefixes "org-glance-tag-config" '("org-glance-tag-config-"))


;;; Generated autoloads from org-glance-tags.el

(autoload 'org-glance-tags "org-glance-tags" "\
Open the all-tags overview: a table of tags with per-tag metrics." t)
(register-definition-prefixes "org-glance-tags" '("org-glance-tags--mtime"))


;;; Generated autoloads from org-glance-utils.el

(register-definition-prefixes "org-glance-utils" '("org-glance"))


;;; Generated autoloads from org-glance-view.el

(register-definition-prefixes "org-glance-view" '("org-glance-view-"))

;;; End of scraped data

(provide 'org-glance-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-glance-autoloads.el ends here
