;;; elsa-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elsa.el

(register-definition-prefixes "elsa" '("elsa-"))


;;; Generated autoloads from elsa-analyser.el

(register-definition-prefixes "elsa-analyser" '("elsa-"))


;;; Generated autoloads from elsa-check.el

(register-definition-prefixes "elsa-check" '("elsa-check"))


;;; Generated autoloads from elsa-declare.el

(register-definition-prefixes "elsa-declare" '("elsa-"))


;;; Generated autoloads from elsa-dependencies.el

(register-definition-prefixes "elsa-dependencies" '("elsa-"))


;;; Generated autoloads from elsa-english.el

(register-definition-prefixes "elsa-english" '("elsa-pluralize"))


;;; Generated autoloads from elsa-error.el

(register-definition-prefixes "elsa-error" '("elsa-"))


;;; Generated autoloads from elsa-explainer.el

(register-definition-prefixes "elsa-explainer" '("elsa-"))


;;; Generated autoloads from elsa-extension-builtin.el

(register-definition-prefixes "elsa-extension-builtin" '("elsa--a"))


;;; Generated autoloads from elsa-extension-cl.el

(register-definition-prefixes "elsa-extension-cl" '("elsa--"))


;;; Generated autoloads from elsa-extension-dash.el

(register-definition-prefixes "elsa-extension-dash" '("elsa-"))


;;; Generated autoloads from elsa-extension-eieio.el

(register-definition-prefixes "elsa-extension-eieio" '("elsa-"))


;;; Generated autoloads from elsa-extension-elsa.el

(register-definition-prefixes "elsa-extension-elsa" '("elsa-"))


;;; Generated autoloads from elsa-extension-flycheck.el

(register-definition-prefixes "elsa-extension-flycheck" '("elsa--analyse:flycheck-define-checker"))


;;; Generated autoloads from elsa-extension-subr.el

(register-definition-prefixes "elsa-extension-subr" '("elsa--analyse:"))


;;; Generated autoloads from elsa-font-lock.el

(autoload 'elsa-setup-font-lock "elsa-font-lock" "\
Setup additional font-locking for Elsa forms." t)
(register-definition-prefixes "elsa-font-lock" '("elsa--"))


;;; Generated autoloads from elsa-form.el

(register-definition-prefixes "elsa-form" '("elsa-"))


;;; Generated autoloads from elsa-functions.el

(register-definition-prefixes "elsa-functions" '("elsa-function-get-"))


;;; Generated autoloads from elsa-log.el

(register-definition-prefixes "elsa-log" '("elsa-"))


;;; Generated autoloads from elsa-lsp.el

(register-definition-prefixes "elsa-lsp" '("elsa-lsp-stdin-loop"))


;;; Generated autoloads from elsa-lsp-core.el

(register-definition-prefixes "elsa-lsp-core" '("append-to-log-file" "elsa-"))


;;; Generated autoloads from elsa-reader.el

(register-definition-prefixes "elsa-reader" '("edebug-" "elsa-"))


;;; Generated autoloads from elsa-rules-list.el

(register-definition-prefixes "elsa-rules-list" '("elsa-check-"))


;;; Generated autoloads from elsa-ruleset.el

(register-definition-prefixes "elsa-ruleset" '("elsa-ruleset"))


;;; Generated autoloads from elsa-scope.el

(register-definition-prefixes "elsa-scope" '("elsa-"))


;;; Generated autoloads from elsa-state.el

(register-definition-prefixes "elsa-state" '("elsa-"))


;;; Generated autoloads from elsa-structure-slot.el

(register-definition-prefixes "elsa-structure-slot" '("elsa-structure-slot"))


;;; Generated autoloads from elsa-type.el

(register-definition-prefixes "elsa-type" '("elsa-"))


;;; Generated autoloads from elsa-type-algebra.el

(register-definition-prefixes "elsa-type-algebra" '("elsa-type-debug"))


;;; Generated autoloads from elsa-type-helpers.el

(register-definition-prefixes "elsa-type-helpers" '("elsa-"))


;;; Generated autoloads from elsa-types.el

(register-definition-prefixes "elsa-types" '("elsa-"))


;;; Generated autoloads from elsa-types-simple.el

(register-definition-prefixes "elsa-types-simple" '("elsa-"))


;;; Generated autoloads from elsa-variable.el

(register-definition-prefixes "elsa-variable" '("elsa-"))

;;; End of scraped data

(provide 'elsa-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elsa-autoloads.el ends here
