;;; table-view-native-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from table-view-native.el

(autoload 'table-view-native-display "table-view-native" "\
Display SPEC in BUFFER backed by the native tvx over SOURCE.
SOURCE is a plist naming the data the backend should own:
  (:kind \"rows\" :rows ROWS)  inline table-view ((id . ID) (cells . ALIST)) rows;
  (:kind \"gen\"  :n N)        N synthetic rows generated in the backend.

When the backend must first be built (`table-view-native-auto-compile'), the
display is *deferred*: BUFFER shows a build placeholder, cargo runs
asynchronously with live output in *tvx-compile*, and the table loads once the
build succeeds (or shows the error if it fails).  When the backend is
unavailable and no build happens, falls back to the pure-elisp path with a
warning (a \"rows\" source still renders; others need the backend).  Returns
the buffer.

(fn BUFFER SOURCE SPEC &optional HANDLERS)")
(register-definition-prefixes "table-view-native" '("table-view-native-"))

;;; End of scraped data

(provide 'table-view-native-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; table-view-native-autoloads.el ends here
