;;; eldoc-eask-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eldoc-eask.el

(autoload 'eldoc-eask-enable "eldoc-eask" "\
Turn on `eldoc-eask'." t)
(autoload 'eldoc-eask-disable "eldoc-eask" "\
Turn off `eldoc-eask'." t)
(register-definition-prefixes "eldoc-eask" '("eldoc-eask--"))

;;; End of scraped data

(provide 'eldoc-eask-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eldoc-eask-autoloads.el ends here
