;;; mijn-email-smtp.el --- Send mail via external msmtp -*- lexical-binding: t; -*-

;; Emacs hands each outgoing message to `msmtp' on stdin; msmtp reads
;; ~/.msmtprc (generated by src/email/setup-email.sh), picks the right
;; account from the From: header, and does the TLS + auth work.
;;
;; Advantages over smtpmail-send-it:
;;   - Emacs main loop is not blocked while msmtp talks to the SMTP server.
;;   - Logs live in ~/.msmtp.log; easy to audit delivery.
;;   - Same config works from the command line (`msmtp -a gmail < file`).

(require 'message)
(require 'sendmail)

(setq sendmail-program (or (executable-find "msmtp") "msmtp")

      ;; Route message sends through the sendmail interface …
      send-mail-function            #'message-send-mail-with-sendmail
      message-send-mail-function    #'message-send-mail-with-sendmail

      ;; … and tell msmtp to use the envelope From: rather than unix $USER,
      ;; so the right ~/.msmtprc account gets picked.
      message-sendmail-f-is-evil    nil
      message-sendmail-envelope-from 'header
      message-sendmail-extra-arguments '("--read-envelope-from"))

;; Identity defaults (per-context overrides live in mu4e-contexts).
(setq user-full-name    mijn-email-user-full-name
      user-mail-address mijn-email-user-address)

(provide 'mijn-email-smtp)
;;; mijn-email-smtp.el ends here
