#!/usr/bin/env bash
# setup-email.sh — one-shot install + config skeleton for the mu4e stack.
# See src/email/email-proposal.md for the design rationale.
#
# Usage:
#   src/email/setup-email.sh             # safe: won't clobber existing rc files
#   src/email/setup-email.sh --force     # overwrite ~/.mbsyncrc and ~/.msmtprc
#
# This script does NOT store your Gmail app password. Run
# src/email/email-credentials.sh after this, once, to insert it into `pass`.

set -euo pipefail

EMAIL="akatovda@gmail.com"
FULL_NAME="Dmitry Akatov"
MAILDIR="${HOME}/Maildir"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

msg() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!  %s\033[0m\n' "$*" >&2; }
die() { printf '\033[1;31mxx  %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- packages ---
msg "Installing system packages (isync mu msmtp pass gnupg)"
missing=()
for pkg in isync mu msmtp pass gnupg; do
  pacman -Q "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  sudo pacman -S --needed --noconfirm "${missing[@]}"
else
  msg "All packages already installed"
fi

# ---------------------------------------------------------------- maildir ----
msg "Creating Maildir skeleton at ${MAILDIR}/gmail"
for sub in INBOX Sent Drafts All Trash Spam; do
  for part in cur new tmp; do
    mkdir -p "${MAILDIR}/gmail/${sub}/${part}"
  done
done

# ---------------------------------------------------------------- pass -------
if ! [[ -d "${PASSWORD_STORE_DIR:-${HOME}/.password-store}" ]]; then
  msg "Initialising pass against your default GPG key"
  key=$(gpg --list-secret-keys --with-colons 2>/dev/null | awk -F: '/^sec/{print $5; exit}')
  [[ -n "$key" ]] || die "No GPG secret key found. Create one with 'gpg --full-generate-key' first."
  pass init "$key"
else
  msg "pass already initialised (${PASSWORD_STORE_DIR:-~/.password-store})"
fi

# ---------------------------------------------------------------- mbsync -----
MBSYNCRC="${HOME}/.mbsyncrc"
if [[ -e "$MBSYNCRC" && $FORCE -eq 0 ]]; then
  warn "$MBSYNCRC exists — skipping (pass --force to overwrite)"
else
  msg "Writing ${MBSYNCRC}"
  cat > "$MBSYNCRC" <<EOF
# ~/.mbsyncrc — generated by src/email/setup-email.sh
# See man:mbsync(1). Credentials come from 'pass show email/gmail'.

IMAPAccount gmail
Host imap.gmail.com
Port 993
User ${EMAIL}
PassCmd "pass show email/gmail"
SSLType IMAPS
AuthMechs LOGIN
PipelineDepth 50

IMAPStore gmail-remote
Account gmail

MaildirStore gmail-local
SubFolders Verbatim
Path ${MAILDIR}/gmail/
Inbox ${MAILDIR}/gmail/INBOX

Channel gmail-inbox
Far :gmail-remote:"INBOX"
Near :gmail-local:INBOX
Create Both
SyncState *
Expunge Both

Channel gmail-sent
Far :gmail-remote:"[Gmail]/Sent Mail"
Near :gmail-local:Sent
Create Both
SyncState *
Expunge Both

Channel gmail-drafts
Far :gmail-remote:"[Gmail]/Drafts"
Near :gmail-local:Drafts
Create Both
SyncState *
Expunge Both

Channel gmail-all
Far :gmail-remote:"[Gmail]/All Mail"
Near :gmail-local:All
Create Both
SyncState *
Expunge None

Channel gmail-trash
Far :gmail-remote:"[Gmail]/Trash"
Near :gmail-local:Trash
Create Both
SyncState *
Expunge Both

Channel gmail-spam
Far :gmail-remote:"[Gmail]/Spam"
Near :gmail-local:Spam
Create Both
SyncState *
Expunge Both

Group gmail
Channel gmail-inbox
Channel gmail-sent
Channel gmail-drafts
Channel gmail-all
Channel gmail-trash
Channel gmail-spam
EOF
fi

# ---------------------------------------------------------------- msmtp ------
MSMTPRC="${HOME}/.msmtprc"
if [[ -e "$MSMTPRC" && $FORCE -eq 0 ]]; then
  warn "$MSMTPRC exists — skipping (pass --force to overwrite)"
else
  msg "Writing ${MSMTPRC}"
  cat > "$MSMTPRC" <<EOF
# ~/.msmtprc — generated by src/email/setup-email.sh
# Credentials come from 'pass show email/gmail'.

defaults
auth on
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile ${HOME}/.msmtp.log

account gmail
host smtp.gmail.com
port 587
from ${EMAIL}
user ${EMAIL}
passwordeval "pass show email/gmail"

account default : gmail
EOF
  chmod 600 "$MSMTPRC"
fi

# ---------------------------------------------------------------- summary ----
cat <<EOF

==> Next steps:
    1. Generate a Gmail app password:
       https://myaccount.google.com/apppasswords  (requires 2FA)
    2. Store it in pass:
       ${HOME}/.emacs.d/src/email/email-credentials.sh
    3. First fetch:
       mbsync -a
    4. Build the search index:
       mu init --maildir=${MAILDIR} --my-address=${EMAIL}
       mu index
    5. In init.el, add:
       (add-to-list 'load-path (expand-file-name "src/email" user-emacs-directory))
       (require 'mijn-email)
       Then: M-x mu4e

    Recurring sync (optional):
       ${HOME}/.emacs.d/src/email/sync-email.sh
       # wire into a systemd user timer if you want background fetch.

    Identity: sent mail will say "${FULL_NAME} <${EMAIL}>".
    Override in ~/.emacs.d/src/email/mijn-email.el if wrong.
EOF
