language: emacs-lisp
env:
  - EMACS=emacs-26
  - EMACS=emacs-snapshot

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS=emacs-26

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b20151e961756602ed9a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false

#  branches:
#    only:
#      - master

before_install:
  - if [ "$EMACS" = 'emacs-26' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get update &&
        sudo apt-get -q install -y emacs26 ;
    fi
  # https://launchpad.net/~ubuntu-elisp/+archive/ppa
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -q update &&
        sudo apt-get -q -f install &&
        sudo apt-get -q install -y emacs-snapshot emacs-snapshot-el ;
    fi
  - git clone --depth=1 https://github.com/cask/cask.git "${HOME}/.cask"

install:
  - ${HOME}/.cask/bin/cask install

script:
  - $EMACS --version
  - ${HOME}/.cask/bin/cask exec buttercup -L .
