;;; s3ed-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from s3ed.el

(register-definition-prefixes "s3ed" '("s3ed-"))


;;; Generated autoloads from s3ed-io.el

(register-definition-prefixes "s3ed-io" '("get-s3ed-tmp-s3-dir" "s3ed-"))


;;; Generated autoloads from s3ed-mode.el

(register-definition-prefixes "s3ed-mode" '("s3ed-"))


;;; Generated autoloads from s3ed-util.el

(register-definition-prefixes "s3ed-util" '("s3ed-"))

;;; End of scraped data

(provide 's3ed-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; s3ed-autoloads.el ends here
