;;; clang-capf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from clang-capf.el

(autoload 'clang-capf "clang-capf" "\
Function used for `completion-at-point-functions' using clang.")
(define-obsolete-function-alias 'cpp-capf #'clang-capf "2020-05-26")
(register-definition-prefixes "clang-capf" '("clang-capf-"))

;;; End of scraped data

(provide 'clang-capf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; clang-capf-autoloads.el ends here
