;;; uv-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uv-mode.el

(autoload 'uv-mode-set "uv-mode" "\
Set python shell virtualenv for PROJECT." t)
(autoload 'uv-mode-unset "uv-mode" "\
Unset python shell virtualenv." t)
(defvar uv-mode nil "\
Non-nil if Uv mode is enabled.
See the `uv-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `uv-mode'.")
(custom-autoload 'uv-mode "uv-mode" nil)
(autoload 'uv-mode "uv-mode" "\
Minor mode for uv virtualenv interaction.

\\{uv-mode-map}

This is a global minor mode.  If called interactively, toggle the `Uv
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='uv-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'uv-mode-auto-activate-hook "uv-mode" "\
Automatically activate UV mode and the project's virtualenv if available.
This function checks for a .venv directory in the project root. If found,
it activates that virtualenv for the current buffer. This is especially
useful when automatically run via `python-mode-hook'.")
(register-definition-prefixes "uv-mode" '("uv-mode-"))

;;; End of scraped data

(provide 'uv-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uv-mode-autoloads.el ends here
