;;; org-glance-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-glance.el

(autoload 'org-glance-init "org-glance" "\
Initialize org-glance in DIRECTORY: bring up the graph store and, when legacy
metadata is detected, warn that `M-x org-glance-migrate' can convert it.

(fn &optional (DIRECTORY org-glance-directory))")
(register-definition-prefixes "org-glance" '("org-glance-"))


;;; Generated autoloads from org-glance-capture.el

(autoload 'org-glance-capture "org-glance-capture" "\
Capture a headline tagged with TAGS (a symbol or list of symbols).

(fn TAGS TITLE &key TEMPLATE FINALIZE)" t)
(function-put 'org-glance-capture 'lisp-indent-function 2)


;;; Generated autoloads from org-glance-core.el

(register-definition-prefixes "org-glance-core" '("org-glance-"))


;;; Generated autoloads from org-glance-datetime-mode.el

(register-definition-prefixes "org-glance-datetime-mode" '("-org-glance-datetime:local-timestamps" "org-glance-datetime-mode"))


;;; Generated autoloads from org-glance-filter.el

(register-definition-prefixes "org-glance-filter" '("org-glance-filter"))


;;; Generated autoloads from org-glance-graph.el

(register-definition-prefixes "org-glance-graph" '("org-glance-"))


;;; Generated autoloads from org-glance-headline.el

(register-definition-prefixes "org-glance-headline" '("org-glance-headline"))


;;; Generated autoloads from org-glance-material.el

(autoload 'org-glance-materialize "org-glance-material" "\
Choose a headline from the graph and materialize it." t)
(autoload 'org-glance-open "org-glance-material" "\
Choose a headline from the graph and open a link inside it." t)
(autoload 'org-glance-extract "org-glance-material" "\
Choose a headline from the graph and extract a key-value pair from it." t)
(register-definition-prefixes "org-glance-material" '("org-glance-"))


;;; Generated autoloads from org-glance-overview.el

(autoload 'org-glance-overview "org-glance-overview" "\
Browse the graph, optionally filtered, in the default view.
Interactively, prompt for a tag (empty input = no tag constraint) and overlay it
on the ambient `org-glance-filter-spec' (default: active headlines).
The landing view is `org-glance-overview-default-view' (the table dashboard by
default); press `T' there to toggle to the other view.  TAG may be a bare tag
(symbol/string) or a full filter plist -- see `org-glance-filter:predicate'.

(fn &optional TAG)" t)
(autoload 'org-glance-agenda "org-glance-overview" "\
Show an `org-agenda' over the graph's scheduled/deadline headlines.
Honours the ambient `org-glance-filter-spec' (default: active headlines)." t)
(register-definition-prefixes "org-glance-overview" '("org-glance-overview"))


;;; Generated autoloads from org-glance-table.el

(autoload 'org-glance-table "org-glance-table" "\
Browse the graph as a sortable, badge-coloured table, optionally filtered.
Interactively, prompt for a tag (empty input = no tag constraint) and overlay it
on the ambient `org-glance-filter-spec' (default: active headlines) -- exactly
like `org-glance-overview', but rendered as a flat table.  Sort with `^' (sorts
by the column at point; repeat toggles direction, `C-u ^' adds a tie-breaker);
act on the row at point with RET/m, o, e.

(fn &optional TAG)" t)
(register-definition-prefixes "org-glance-table" '("org-glance-table"))


;;; Generated autoloads from org-glance-tag-config.el

(autoload 'org-glance-tag-config-edit "org-glance-tag-config" "\
Open the tag-configuration file for editing, creating a stub if absent." t)
(register-definition-prefixes "org-glance-tag-config" '("org-glance-tag-config-"))


;;; Generated autoloads from org-glance-tags.el

(autoload 'org-glance-tags "org-glance-tags" "\
Open the all-tags overview: a table of tags with per-tag metrics." t)
(register-definition-prefixes "org-glance-tags" '("org-glance-tags--mtime"))


;;; Generated autoloads from org-glance-ui.el

(autoload 'org-glance-transient "org-glance-ui" "\
Perform action on selected view/headlines

(fn)" t)


;;; Generated autoloads from org-glance-utils.el

(register-definition-prefixes "org-glance-utils" '("org-glance"))


;;; Generated autoloads from org-glance-view.el

(register-definition-prefixes "org-glance-view" '("org-glance-view-"))

;;; End of scraped data

(provide 'org-glance-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-glance-autoloads.el ends here
