;;; eask-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eask-mode.el

(autoload 'eask-mode "eask-mode" "\
Major mode for editing Eask files.

(fn)" t)
(add-to-list 'auto-mode-alist '("/Easkfile[.0-9]*\\'" . eask-mode))
(add-to-list 'auto-mode-alist '("/Eask[.0-9]*\\'" . eask-mode))
(register-definition-prefixes "eask-mode" '("eask-mode-"))

;;; End of scraped data

(provide 'eask-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eask-mode-autoloads.el ends here
