;;; agnostic-llm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agnostic-llm.el

(autoload 'agnostic-llm-show-last-response "agnostic-llm" "\
Show the current claude session's latest response in another window.
Must be invoked from a `*claude:PROJECT*' vterm.  Locates that buffer's
session JSONL (newest .jsonl under its project dir) without writing
anything to disk, extracts the most recent assistant turn, and renders it
via `agnostic-llm-response-render-function' into a reused
`*claude-response:LABEL*' buffer shown in another window, with point at
the top." t)
(autoload 'agnostic-llm "agnostic-llm" "\
Open Claude CLI in a vterm buffer named *claude:project*.
With non-nil USER-ROOT, target that directory instead of the current
project.
Without prefix: reuse the existing buffer, or create one.
With \\[universal-argument]: new buffer, continue session if possible.
With \\[universal-argument] \\[universal-argument]: new buffer, fresh session.

(fn &optional USER-ROOT)" t)
(autoload 'agnostic-llm-vterm-here "agnostic-llm" "\
Open or switch to a vterm buffer in the current window.
Without prefix: switch to the last *vterm:LABEL* buffer for the project,
or create one if none exist.
With prefix: always create a new vterm buffer." t)
(autoload 'agnostic-llm-prompt-bubble "agnostic-llm" "\
Open a bubble: throwaway prompt that streams the reply inline.
Thin wrapper around `agnostic-llm-prompt' with the prefix argument
preset, so it is directly bindable and transient-invokable without
`universal-argument'.

The bubble runs `claude -p', which is non-interactive: any tool that
would normally ask you something (permission prompts, AskUserQuestion)
is auto-failed by the CLI before reaching us.  If a turn needs that kind
of interaction, promote with \\<agnostic-llm-prompt-mode-map>\\[agnostic-llm--bubble-promote] to a `*claude:PROJECT*' vterm
that resumes the same session." t)
(autoload 'agnostic-llm-prompt-send "agnostic-llm" "\
Send the contents of the prompt buffer to Claude.
In bubble mode: run `claude -p' as a subprocess and stream the reply
into the same bubble.  Otherwise: hand off to the project's claude
vterm session (queues if busy)." t)
(autoload 'agnostic-llm-prompt "agnostic-llm" "\
Open a multi-line prompt buffer for Claude.
Pre-populates context based on the current state:
- Active region: inserts a file/region context prefix
- Otherwise: inserts a file+line context prefix

With \\[universal-argument] ARG: bubble mode.  Opens a fresh throwaway
bubble with no file-context prefix; on send, runs `claude -p <prompt>'
as a subprocess and streams the reply into the same bubble.
Nothing is saved to prompt history and the main claude vterm is
untouched.

(fn &optional ARG)" t)
(autoload 'agnostic-llm-prompt-history "agnostic-llm" "\
Browse this project's saved prompt files.
Picks a prompt via `completing-read' and opens it in the bubble
for editing and re-sending." t)
(autoload 'agnostic-llm-prompt-resume "agnostic-llm" "\
Re-open the most recent saved prompt for this project in the bubble." t)
(autoload 'agnostic-llm-switch-buffer "agnostic-llm" "\
Switch to another claude buffer." t)
(autoload 'agnostic-llm-next-buffer "agnostic-llm" "\
Switch current window to the next claude buffer." t)
(autoload 'agnostic-llm-previous-buffer "agnostic-llm" "\
Switch current window to the previous claude buffer." t)
(autoload 'agnostic-llm-grep-annotations "agnostic-llm" "\
Grep all TODO/FIXME/HACK/XXX comments in the current project." t)
(autoload 'agnostic-llm-set-default-model "agnostic-llm" "\
Set MODEL as the default for new claude sessions and persist it.
Empty input clears the default (claude will pick).  The value is saved
via `customize-save-variable', so it survives Emacs restarts.

Per-invocation overrides via the menu's `-m' switch are unaffected.

(fn MODEL)" t)
(autoload 'agnostic-llm-toggle-vterm-claude "agnostic-llm" "\
Toggle current window between `*vterm:PROJECT*' and `*claude:PROJECT*'.
Switches to the counterpart of the current buffer, creating it in the
current window if missing.  When the current buffer is neither, jump
to the project's vterm first (reusing or spawning)." t)
(autoload 'agnostic-llm-describe-at-point "agnostic-llm" "\
Ask Claude to describe the symbol at point or the active region.
Spawns a bubble seeded with a prompt referencing the visiting file and
line(s), and auto-sends.  If the buffer isn't visiting a file, the
buffer name is used as context instead." t)
(register-definition-prefixes "agnostic-llm" '("agnostic-llm-"))

;;; End of scraped data

(provide 'agnostic-llm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agnostic-llm-autoloads.el ends here
