(defun nginx--reload ()
  (interactive)
  (eshell)
  (goto-char (point-max))
  (eshell-kill-input)
  (insert "sudo nginx -s reload")
  (eshell-send-input))

(defun nginx--stop ()
  (interactive)
  (eshell)
  (goto-char (point-max))
  (eshell-kill-input)
  (insert "sudo nginx -s stop")
  (eshell-send-input))

(defun nginx--start ()
  (interactive)
  (eshell)
  (goto-char (point-max))
  (eshell-kill-input)
  (insert "sudo nginx")
  (eshell-send-input))

(defun apache--restart ()
  (interactive)
  (eshell)
  (goto-char (point-max))
  (eshell-kill-input)
  (insert "sudo apachectl -k restart")
  (eshell-send-input))

(defun apache--stop ()
  (interactive)
  (eshell)
  (goto-char (point-max))
  (eshell-kill-input)
  (insert "sudo apachectl stop")
  (eshell-send-input))

(defun apache--start ()
  (interactive)
  (eshell)
  (goto-char (point-max))
  (eshell-kill-input)
  (insert "sudo apachectl start")
  (eshell-send-input))

(provide 'init-eshell-commands)
