;;; company-eask-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-eask.el

(autoload 'company-eask "company-eask" "\
Company backend for Eask-file.

Arguments COMMAND and ARG are standard arguments from `company-mode`.

(fn COMMAND &optional ARG &rest _)" t)
(register-definition-prefixes "company-eask" '("company-eask-"))

;;; End of scraped data

(provide 'company-eask-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-eask-autoloads.el ends here
