;;; eask-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eask-api.el

(autoload 'eask-api-setup "eask-api" "\
Set up for `eask-api'.

Since this is the entry, we only check for the project root and current
workspace.  The full version uses function `locate-dominating-file' to search
for Eask-files, but we don't want to do that for our entry.")
(register-definition-prefixes "eask-api" '("eask-api-"))


;;; Generated autoloads from eask-core.el

(register-definition-prefixes "eask-core" '("eask-"))

;;; End of scraped data

(provide 'eask-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eask-autoloads.el ends here
