;;; flymake-ruff-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-ruff.el

(autoload 'flymake-ruff-load "flymake-ruff" "\
Load hook for the current buffer to tell flymake to run checker." t)
(autoload 'flymake-ruff-goto-doc "flymake-ruff" "\
Browse to the documentation for the Ruff rule on a Flymake diagnostic line.
Scans the Flymake diagnostic at point for a \"RULE123\"-style code and
browses to its documentation at https://docs.astral.sh/ruff/rules." t)
(register-definition-prefixes "flymake-ruff" '("flymake-ruff-"))

;;; End of scraped data

(provide 'flymake-ruff-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-ruff-autoloads.el ends here
