;;; flymake-python-pyflakes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-python-pyflakes.el

(autoload 'flymake-python-pyflakes-load "flymake-python-pyflakes" "\
Configure flymake mode to check the current buffer's python syntax using pyflakes." t)
(register-definition-prefixes "flymake-python-pyflakes" '("flymake-python-pyflakes-"))

;;; End of scraped data

(provide 'flymake-python-pyflakes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-python-pyflakes-autoloads.el ends here
