;;; bluetooth-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bluetooth.el

(autoload 'bluetooth-init "bluetooth" "\
Initialize Bluetooth mode.")
(autoload 'bluetooth-list-devices "bluetooth" "\
Display a list of Bluetooth devices.
This function starts Bluetooth mode which offers an interface
offering device management functions, e.g. pairing, connecting,
scanning the bus, displaying device info etc." t)
(register-definition-prefixes "bluetooth" '("bluetooth-"))


;;; Generated autoloads from bluetooth-battery.el

(autoload 'bluetooth-battery-init "bluetooth-battery" "\
Initialize the bluetooth-battery plugin.
The Bluetooth mode menu must be passed in MENU.

This plugin shows a device's battery level in the device
information view of Bluetooth mode, if the device implements the
battery interface.  It also warns about low battery levels if
‘bluetooth-battery-display-warning’ is t.  You can customize the
warning level with ‘bluetooth-battery-warning-level’.  This is an
inclusive level, so the warning will be displayed if the battery
percentage is at this level or lower.

(fn MENU)")
(register-definition-prefixes "bluetooth-battery" '("bluetooth-battery-"))


;;; Generated autoloads from bluetooth-device.el

(register-definition-prefixes "bluetooth-device" '("bluetooth-device"))


;;; Generated autoloads from bluetooth-lib.el

(register-definition-prefixes "bluetooth-lib" '("bluetooth-"))


;;; Generated autoloads from bluetooth-pa.el

(register-definition-prefixes "bluetooth-pa" '("bluetooth-pa-"))


;;; Generated autoloads from bluetooth-plugin.el

(register-definition-prefixes "bluetooth-plugin" '("bluetooth-plugin-"))


;;; Generated autoloads from bluetooth-uuid.el

(register-definition-prefixes "bluetooth-uuid" '("bluetooth-uuid-"))

;;; End of scraped data

(provide 'bluetooth-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bluetooth-autoloads.el ends here
