;;; unison-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from unison-ts-font-lock.el

(register-definition-prefixes "unison-ts-font-lock" '("unison-ts-font-lock"))


;;; Generated autoloads from unison-ts-indent-rules.el

(register-definition-prefixes "unison-ts-indent-rules" '("unison-ts-"))


;;; Generated autoloads from unison-ts-install.el

(register-definition-prefixes "unison-ts-install" '("unison-ts-"))


;;; Generated autoloads from unison-ts-mode.el

(autoload 'unison-ts-mode "unison-ts-mode" "\
Major mode for editing Unison, powered by tree-sitter.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.u\\'" . unison-ts-mode))
(autoload 'unison-ts-mode-setup-eglot "unison-ts-mode" "\
Set up eglot for `unison-ts-mode'.
Call this from your init file:
  (with-eval-after-load \\='unison-ts-mode
    (with-eval-after-load \\='eglot
      (unison-ts-mode-setup-eglot)))")
(autoload 'unison-ts-mode-setup-lsp "unison-ts-mode" "\
Set up lsp-mode for `unison-ts-mode'.
Call this from your init file:
  (with-eval-after-load \\='unison-ts-mode
    (with-eval-after-load \\='lsp-mode
      (unison-ts-mode-setup-lsp)))")
(register-definition-prefixes "unison-ts-mode" '("unison-ts-"))


;;; Generated autoloads from unison-ts-repl.el

(autoload 'unison-ts-repl "unison-ts-repl" "\
Switch to UCM REPL buffer, starting UCM headless if needed.
Uses MCP protocol to communicate with a single UCM headless process,
which also serves LSP for eglot. This avoids codebase lock conflicts
by ensuring only one UCM process runs at a time." t)
(autoload 'unison-ts-add "unison-ts-repl" "\
Add definitions from the current file to the codebase via MCP." t)
(autoload 'unison-ts-update "unison-ts-repl" "\
Update existing definitions in the codebase via MCP." t)
(autoload 'unison-ts-test "unison-ts-repl" "\
Run tests in the current project via MCP." t)
(autoload 'unison-ts-eval "unison-ts-repl" "\
Evaluate a Unison expression via MCP.
EXPR is evaluated using the typecheck-code tool with > prefix.
Works for both pure functions and IO actions.

(fn EXPR)" t)
(autoload 'unison-ts-run "unison-ts-repl" "\
Run an IO action from the codebase via MCP.
For pure expressions, use `unison-ts-eval' instead." t)
(autoload 'unison-ts-watch "unison-ts-repl" "\
Typecheck current file and show results via MCP." t)
(autoload 'unison-ts-load "unison-ts-repl" "\
Load current file into the codebase via MCP." t)
(autoload 'unison-ts-send-region "unison-ts-repl" "\
Send the region between START and END to UCM via MCP.

(fn START END)" t)
(autoload 'unison-ts-send-definition "unison-ts-repl" "\
Send the definition at point to UCM via MCP." t)
(register-definition-prefixes "unison-ts-repl" '("unison-ts-"))

;;; End of scraped data

(provide 'unison-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; unison-ts-mode-autoloads.el ends here
